name: Build SunamoBts

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoBts
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoBts/SunamoBts.csproj

    - name: Build
      run: dotnet build SunamoBts/SunamoBts.csproj --configuration Release --no-restore

  test:
    name: Test SunamoBts.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoBts.Tests/SunamoBts.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoBts.Tests/SunamoBts.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoBts.Tests/SunamoBts.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
